### ISSUE TITLE
ska_helpers.logging is not doing the right thing when logging has been configured already

### ISSUE THREAD

**Issue by javierggt** [sot/ska_helpers#24]
The standard pattern for logging is that the logging is configured at the top-level in the `main` function. We have tried with `pyaks.logging` and now with `ska_helpers.logging` to give default configuration for loggers inside packages.

However, `ska_helpers.logging` does not behave as expected. I saw issues with this, I think with aca_view, and simplified it to the following script to demonstrate the issue:
``` python
import ska_helpers.logging
import logging
logging.basicConfig(level='DEBUG')
_ = ska_helpers.logging.basic_logger(name='maude', level=logging.WARNING)
logger = logging.getLogger('maude')
logger.warning('this is a warning')
logger.debug('this is a debug statement')

```

## What I expect

I expect that all loggers are configured after the call to `logging.basicConfig(level='DEBUG')`, and that includes the `maude` logger.

# What happens

The config the `ska_helpers.logging.basic_logger` overrides the logging level, so now the debug statements do not show. It also does something that causes the warning messages to be duplicated. This is what I see:

```
2022-08-30 11:08:34,901 <module>: this is a warning
WARNING:maude:this is a warning
```

**Comment by taldcroft** [comment]
The behavior you showed is what I would expect and what is intended. 

IMO the setup of the `root` logger should never influence another package logger. Essentially if some random dependent package decides to configure the GLOBAL root logger, that should not change the `maude` logger. Otherwise we can never fully control `maude` logging because any other package we import can change the root logger.

IMO the global root logger via `logging.basicConfig()` (which is shared by every single package) is a bad idea and should be entirely avoided in all situations.

**Comment by taldcroft** [comment]
For more technical detail, the reason the root logger does not influence the `maude` logger is that they are in a different namespace. The `logging` root logger is named `"root"`, so that `"maude"` does not delegate or share the root in any way:
```
class RootLogger(Logger):
    """
    A root logger is not that different to any other logger, except that
    it must have a logging level and there is only one instance of it in
    the hierarchy.
    """
    def __init__(self, level):
        """
        Initialize the logger with the name "root".
        """
        Logger.__init__(self, "root", level)

    def __reduce__(self):
        return getLogger, ()
```

**Comment by javierggt** [comment]
Then I completely disagree with what you expected and intended. I do not see a reason why it should ever print a message twice. At the very least that is a bug.

**Comment by javierggt** [comment]
I will see if I give a different example not using basicConfig, but the bottomline is that it should be possible to configure logging at the top level, and there should be a way for me to shut off any logger at the top level without a priory knowing the names of all loggers.

To me, it is unacceptable that a module overrides a configuration from my main function.

**Comment by javierggt** [comment]
And by the way:

>  if some random dependent package decides to configure the GLOBAL root logger, that should not change the maude logger.

No module EVER should be changing the global root logger, and doing that should be considered a bug, so it is pointless to protect agains that. The basicConfig functions is intented to be called at the top level of your **script**, basically the `main` function.

**Comment by taldcroft** [comment]
> No module EVER should be changing the global root logger, and doing that should be considered a bug, so it is pointless to protect against that. 

Unfortunately we do have to protect against bugs in other packages, especially this one we've seen before in numba:

```
In [1]: from logging import basicConfig
In [2]: basicConfig(level='DEBUG')
In [3]: import numba
In [4]: @numba.jit()
   ...: def add_one(x):
   ...:     return x + 1
   ...: 

In [5]: add_one(1)
DEBUG:numba.core.byteflow:bytecode dump:
>          0	NOP(arg=None, lineno=3)
           2	LOAD_FAST(arg=0, lineno=3)
           4	LOAD_CONST(arg=1, lineno=3)
           6	BINARY_ADD(arg=None, lineno=3)
           8	RETURN_VALUE(arg=None, lineno=3)
DEBUG:numba.core.byteflow:pending: deque([State(pc_initial=0 nstack_initial=0)])
DEBUG:numba.core.byteflow:stack: []
DEBUG:numba.core.byteflow:dispatch pc=0, inst=NOP(arg=None, lineno=3)
DEBUG:numba.core.byteflow:stack []
DEBUG:numba.core.byteflow:dispatch pc=2, inst=LOAD_FAST(arg=0, lineno=3)
DEBUG:numba.core.byteflow:stack []
DEBUG:numba.core.byteflow:dispatch pc=4, inst=LOAD_CONST(arg=1, lineno=3)
DEBUG:numba.core.byteflow:stack ['$x2.0']
DEBUG:numba.core.byteflow:dispatch pc=6, inst=BINARY_ADD(arg=None, lineno=3)
DEBUG:numba.core.byteflow:stack ['$x2.0', '$const4.1']
DEBUG:numba.core.byteflow:dispatch pc=8, inst=RETURN_VALUE(arg=None, lineno=3)
DEBUG:numba.core.byteflow:stack ['$6binary_add.2']
DEBUG:numba.core.byteflow:end state. edges=[]
DEBUG:numba.core.byteflow:-------------------------Prune PHIs-------------------------
DEBUG:numba.core.byteflow:Used_phis: defaultdict(<class 'set'>, {State(pc_initial=0 nstack_initial=0): set()})
DEBUG:numba.core.byteflow:defmap: {}
DEBUG:numba.core.byteflow:phismap: defaultdict(<class 'set'>, {})
DEBUG:numba.core.byteflow:changing phismap: defaultdict(<class 'set'>, {})
DEBUG:numba.core.byteflow:keep phismap: {}
DEBUG:numba.core.byteflow:new_out: defaultdict(<class 'dict'>, {})
DEBUG:numba.core.byteflow:----------------------DONE Prune PHIs-----------------------
DEBUG:numba.core.byteflow:block_infos State(pc_initial=0 nstack_initial=0):
AdaptBlockInfo(insts=((0, {}), (2, {'res': '$x2.0'}), (4, {'res': '$const4.1'}), (6, {'lhs': '$x2.0', 'rhs': '$const4.1', 'res': '$6binary_add.2'}), (8, {'retval': '$6binary_add.2', 'castval': '$8return_value.3'})), outgoing_phis={}, blockstack=(), active_try_block=None, outgoing_edgepushed={})
DEBUG:numba.core.interpreter:label 0:
    x = arg(0, name=x)                       ['x']
    $const4.1 = const(int, 1)                ['$const4.1']
    $6binary_add.2 = x + $const4.1           ['$6binary_add.2', '$const4.1', 'x']
    $8return_value.3 = cast(value=$6binary_add.2) ['$6binary_add.2', '$8return_value.3']
    return $8return_value.3                  ['$8return_value.3']

DEBUG:numba.core.ssa:==== SSA block analysis pass on 0
DEBUG:numba.core.ssa:Running <numba.core.ssa._GatherDefsHandler object at 0x7fd9e0120940>
DEBUG:numba.core.ssa:on stmt: x = arg(0, name=x)
DEBUG:numba.core.ssa:on stmt: $const4.1 = const(int, 1)
DEBUG:numba.core.ssa:on stmt: $6binary_add.2 = x + $const4.1
DEBUG:numba.core.ssa:on stmt: $8return_value.3 = cast(value=$6binary_add.2)
DEBUG:numba.core.ssa:on stmt: return $8return_value.3
DEBUG:numba.core.ssa:defs defaultdict(<class 'list'>,
            {'$6binary_add.2': [<numba.core.ir.Assign object at 0x7fd9e0120250>],
             '$8return_value.3': [<numba.core.ir.Assign object at 0x7fd9e0120d00>],
             '$const4.1': [<numba.core.ir.Assign object at 0x7fd9e01364f0>],
             'x': [<numba.core.ir.Assign object at 0x7fd9e0136250>]})
DEBUG:numba.core.ssa:SSA violators set()
2
```

**Comment by taldcroft** [comment]
It's worth noting that I don't think `numba` explicitly does anything with the root logger except *use* it for logging, see below. This may be a common *lazy* pattern in packages since setting up a logger yourself requires writing your own function (which I have done at least twice) and then using the namespace logger everywhere instead of the root.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/348089/187500769-01c4e7bd-3230-4562-b7d5-3f21cb06a858.png">

It all boils down to the inexplicable decision of `basicConfig` to default to a global root logger and not expose a way to use that convenience function to define or update a named logger.

**Comment by taldcroft** [comment]
> there should be a way for me to shut off any logger at the top level without a priory knowing the names of all loggers.

AFAIK that is contrary to the basic design of `logging`. If there is a logger / handler defined in a package or module (e.g. maude) which is enabled to handle a logging request, then that message is emitted and there is no going back. Then if the logger `propagate` is `True` (which is the case by default), then the message gets passed up to the ancestors (https://docs.python.org/3/library/logging.html#logging.Logger).

**Comment by taldcroft** [comment]
Another example I just ran into of a package lazily using the root logger. In IPython the `parso` package (whatever that is) does this. After calling `basicConfig(level='DEBUG')` in my session I get this badness at the command prompt:
```
In [14]: log<TAB>
DEBUG:parso.python.diff:diff parser start
DEBUG:parso.python.diff:line_lengths old: 1; new: 1
DEBUG:parso.python.diff:-> code[replace] old[1:1] new[1:1]
DEBUG:parso.python.diff:parse_part from 1 to 1 (to 0 in part parser)
DEBUG:parso.python.diff:diff parser end
DEBUG:parso.cache:pickle loaded: /Users/aldcroft/miniconda3/envs/ska3/lib/python3.8/site-packages/jedi/third_party/typeshed/stdlib/2and3/builtins.pyi
DEBUG:parso.cache:pickle loaded: /Users/aldcroft/miniconda3/envs/ska3/lib/python3.8/site-packages/jedi/third_party/typeshed/stdlib/3/sys.pyi
```

**Comment by taldcroft** [comment]
This diagram explains why the root logger never got the DEBUG message: https://docs.python.org/3/howto/logging.html#logging-flow

If the `maude` logger level is set to WARNING then it does not pass anything below WARNING on to parent loggers. But in the original example it does pass on the `logger.warning()` message to the root logger from `basicConfig`.

So I'm fully back to expecting the output you showed.

**Comment by javierggt** [comment]
> Unfortunately we do have to protect against bugs in other packages, especially this one we've seen before in numba

I do not see a bug there. It is working exactly as advertised. It is annoying because it is verbose, but it is exactly as expected. It seems you and I do not agree on what is _expected_.

You do not like basicConfig because it enables/disables _everything_, but that is just what it does. I agree that top-level scripts should use a bit more fine-grained configuration, and maybe there is a need for a method to make the top-level config a bit easier.

On the other hand, while working with aca_view I have tried to have a proper configuration according to the intentions of the framework, and in the end the packages that have these custom functions end up misbehaving in some way. In this case, I do not blame the framework.

**Comment by javierggt** [comment]
For example, configure logging first with:
```
settings = {
        'version': 1,
        'formatters': {
            'default': {
                'format': 'BLA %(levelname)-8s %(processName)-10s/%(threadName)s - %(name)s.%(module)-30s %(funcName)-20s - %(message)s'  # noqa
            }
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'default',
                'level': 'DEBUG'
            },
        },
        'loggers': {
            'maude': {
                'level': 'INFO',
                #'handlers': ['console'],
                #'propagate': False
             }
        },
        'root': {
            'level': 'WARNING',
            'handlers': ['console']
        }
    }


logging.config.dictConfig(settings)
_  = ska_helpers.logging.basic_logger(name='maude', level=logging.DEBUG)
```

and you will see that the later statement overrides the behavior that I explicitly set at top level.

The reason again is that I did not specify `propagate = False`.

I am sorry, but at this point there is nothing you can say to justify it other than it is what you want. And I will accept that, but let it be noted.

**Comment by javierggt** [comment]
This is a minimal configuration that, if I do it at the top level of a script, I expect no module should override:
```
settings = {
    'version': 1,
    'loggers': {
        'maude': {
            'level': 'INFO',
        }
    },
    'root': {
        'level': 'WARNING',
    }
}


logging.config.dictConfig(settings)
```

This function overrides it. As I said above, you and I seem to have different expectations.

**Comment by taldcroft** [comment]
About expected behavior, back to this:
```
In [1]: import logging
In [2]: logging.basicConfig(level='DEBUG')
In [3]: import numba
In [4]: @numba.jit()
   ...: def add_one(x):
   ...:     return x + 1
In [5]: y = add_one(1)
In [6]: logger.debug('hello world!')
```
I bet a large sum that everyone would expect `DEBUG:root:hello world!`. Having dug into this, it is true that I understand and (now) expect a huge mess of output from numba.

Why I call this a bug is that it means that your script *cannot effectively use* the root logger for debug output if you happen to be using any numba functions because your output is polluted by unwanted numba logging.

**Comment by taldcroft** [comment]
Remember the `basic_logger` function is a very thin wrapper around `basicConfig`, which advertises (https://docs.python.org/3/library/logging.html#logging.basicConfig) that "This function does nothing if the root logger already has handlers configured, unless the keyword argument force is set to True.".

So you are saying that the statement above is not correct? I see this concern now, which I think is different from the issue in the top description.

**Comment by taldcroft** [comment]
Ah, in your example settings there are no handlers defined, so then `basicConfig` probably feels free to override the settings.

To turn this around, what should the `maude` or `kadi` packages do allow for logging that would work for you?

**Comment by javierggt** [comment]
basically I copied the settings from aca_view, so my latest two are what I would have expected.

Strictly speaking, my original configuration looked something like:
```
settings = {
        'version': 1,
        'formatters': {
            'default': {
                'format': 'BLA %(levelname)-8s %(processName)-10s/%(threadName)s - %(name)s.%(module)-30s %(funcName)-20s - %(message)s'  # noqa
            }
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'default',
                'level': 'DEBUG'
            },
        },
        'loggers': {
            'aca_view': {
                'level': 'INFO',
                'handlers': ['console'],
                'propagate': False
             }
            'aca_view.data': {
                'level': 'DEBUG',
             }
        },
        'root': {
            'level': 'WARNING',
            'handlers': ['console']
        }
    }


logging.config.dictConfig(settings)
#_ = ska_helpers.logging.basic_logger(name='maude', level=logging.DEBUG)
```

Note that the maude logger is not mentioned, and that is because I do not care about it, so it should be shut off. Normally, this config would shut everything off except for my modules.

Maude was doing something non-standard at some point, and that is why I had to add it. Now ska_helpers would not only require that I explicitly shut off maude, but that I assign a handler plus propagate=False so ska_helpers doesn't revive it. And I would have to start adding any other logger where the developer decides to have a default level other than warning.

I do not want to have to add other loggers to the settings just to shut them off.

Even if you say the logging level will usually not be set to anything but warning, I guess you understand why I do not like it.
